### ISSUE TITLE
Adak gets stuck on login

### ISSUE THREAD

**Issue by sisuani** [GGP1/adak#4]
When I try to login with an incorrect password, the app got stuck.
I think this happens because Adak is locking the mutex twice.

- From the auth package:
```
func (s *session) Login(ctx context.Context, w http.ResponseWriter, r *http.Request, email, password string) error {
	s.Lock()
	defer s.Unlock()

...

	// Check if the email exists and if it is verified
	if err := s.DB.GetContext(ctx, &user, query, email); err != nil {
		s.loginDelay(ip)
		return errors.New("invalid email or password")
	}
...
```

- Here is locking it again:
```
func (s *session) loginDelay(ip string) {
	s.Lock()
	defer s.Unlock()
...
}
```

**Comment by GGP1** [comment]
You are right, the second Lock is waiting for the first one to finish (blocks forever). I've fixed it, thanks for your report.
